### BUSCAR TODOS OS PONTOS

GET http://localhost:5000/get/pontos

### CADASTRAR NOVO PONTO

POST http://localhost:5000/register/pontos
Content-Type: application/json

{

    "latitude": "18.91814500",
    "longitude": "48.26453700"
}

### CONSTRUIR MAPA

GET http://localhost:5000/mapa